/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColorGridGame__factory } from "./ColorGridGame__factory";
export { ColorGridGameBase__factory } from "./ColorGridGameBase__factory";
export { ColorGridGameTest__factory } from "./ColorGridGameTest__factory";
