/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ColorGridGameBaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "INITIAL_PRICE"
      | "canClaimTimeBank"
      | "claimColorBank"
      | "claimTimeBank"
      | "claimableBalance"
      | "colorBank"
      | "colorCount"
      | "colorRewardClaimed"
      | "colorWins"
      | "currentPrice"
      | "currentRound"
      | "getBoard"
      | "getColorFillCounts"
      | "gridCells"
      | "gridSide"
      | "idleThreshold"
      | "lastColorWinRound"
      | "lastPaintTimestamp"
      | "lastPainter"
      | "paintCell"
      | "strokesPerRound"
      | "timeBank"
      | "totalStrokesPerRound"
      | "withdrawRewards"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CellPainted"
      | "ColorBankTriggered"
      | "RewardsWithdrawn"
      | "TimeBankReady"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "INITIAL_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canClaimTimeBank",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimColorBank",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeBank",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "colorBank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "colorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "colorRewardClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "colorWins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRound",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBoard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getColorFillCounts",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gridCells", values?: undefined): string;
  encodeFunctionData(functionFragment: "gridSide", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "idleThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastColorWinRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPaintTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPainter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paintCell",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strokesPerRound",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "timeBank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalStrokesPerRound",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRewards",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "INITIAL_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canClaimTimeBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimColorBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "colorBank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "colorCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "colorRewardClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "colorWins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getColorFillCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gridCells", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gridSide", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "idleThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastColorWinRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPaintTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPainter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paintCell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strokesPerRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeBank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalStrokesPerRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRewards",
    data: BytesLike
  ): Result;
}

export namespace CellPaintedEvent {
  export type InputTuple = [
    painter: AddressLike,
    cellIndex: BigNumberish,
    colorId: BigNumberish,
    pricePaid: BigNumberish
  ];
  export type OutputTuple = [
    painter: string,
    cellIndex: bigint,
    colorId: bigint,
    pricePaid: bigint
  ];
  export interface OutputObject {
    painter: string;
    cellIndex: bigint;
    colorId: bigint;
    pricePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ColorBankTriggeredEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    colorId: BigNumberish,
    reward: BigNumberish,
    totalStrokes: BigNumberish
  ];
  export type OutputTuple = [
    roundId: bigint,
    colorId: bigint,
    reward: bigint,
    totalStrokes: bigint
  ];
  export interface OutputObject {
    roundId: bigint;
    colorId: bigint;
    reward: bigint;
    totalStrokes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsWithdrawnEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeBankReadyEvent {
  export type InputTuple = [winner: AddressLike, reward: BigNumberish];
  export type OutputTuple = [winner: string, reward: bigint];
  export interface OutputObject {
    winner: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ColorGridGameBase extends BaseContract {
  connect(runner?: ContractRunner | null): ColorGridGameBase;
  waitForDeployment(): Promise<this>;

  interface: ColorGridGameBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  INITIAL_PRICE: TypedContractMethod<[], [bigint], "view">;

  canClaimTimeBank: TypedContractMethod<[], [boolean], "view">;

  claimColorBank: TypedContractMethod<
    [roundId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTimeBank: TypedContractMethod<[], [void], "nonpayable">;

  claimableBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  colorBank: TypedContractMethod<[], [bigint], "view">;

  colorCount: TypedContractMethod<[], [bigint], "view">;

  colorRewardClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  colorWins: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        colorId: bigint;
        reward: bigint;
        totalStrokes: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  currentPrice: TypedContractMethod<[], [bigint], "view">;

  currentRound: TypedContractMethod<[], [bigint], "view">;

  getBoard: TypedContractMethod<[], [bigint[]], "view">;

  getColorFillCounts: TypedContractMethod<[], [bigint[]], "view">;

  gridCells: TypedContractMethod<[], [bigint], "view">;

  gridSide: TypedContractMethod<[], [bigint], "view">;

  idleThreshold: TypedContractMethod<[], [bigint], "view">;

  lastColorWinRound: TypedContractMethod<[], [bigint], "view">;

  lastPaintTimestamp: TypedContractMethod<[], [bigint], "view">;

  lastPainter: TypedContractMethod<[], [string], "view">;

  paintCell: TypedContractMethod<
    [cellIndex: BigNumberish, colorId: BigNumberish],
    [void],
    "payable"
  >;

  strokesPerRound: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;

  timeBank: TypedContractMethod<[], [bigint], "view">;

  totalStrokesPerRound: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawRewards: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "INITIAL_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canClaimTimeBank"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimColorBank"
  ): TypedContractMethod<[roundId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeBank"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "colorBank"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "colorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "colorRewardClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "colorWins"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        colorId: bigint;
        reward: bigint;
        totalStrokes: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBoard"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getColorFillCounts"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "gridCells"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gridSide"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "idleThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastColorWinRound"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPaintTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPainter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paintCell"
  ): TypedContractMethod<
    [cellIndex: BigNumberish, colorId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "strokesPerRound"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "timeBank"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStrokesPerRound"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CellPainted"
  ): TypedContractEvent<
    CellPaintedEvent.InputTuple,
    CellPaintedEvent.OutputTuple,
    CellPaintedEvent.OutputObject
  >;
  getEvent(
    key: "ColorBankTriggered"
  ): TypedContractEvent<
    ColorBankTriggeredEvent.InputTuple,
    ColorBankTriggeredEvent.OutputTuple,
    ColorBankTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsWithdrawn"
  ): TypedContractEvent<
    RewardsWithdrawnEvent.InputTuple,
    RewardsWithdrawnEvent.OutputTuple,
    RewardsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TimeBankReady"
  ): TypedContractEvent<
    TimeBankReadyEvent.InputTuple,
    TimeBankReadyEvent.OutputTuple,
    TimeBankReadyEvent.OutputObject
  >;

  filters: {
    "CellPainted(address,uint8,uint8,uint256)": TypedContractEvent<
      CellPaintedEvent.InputTuple,
      CellPaintedEvent.OutputTuple,
      CellPaintedEvent.OutputObject
    >;
    CellPainted: TypedContractEvent<
      CellPaintedEvent.InputTuple,
      CellPaintedEvent.OutputTuple,
      CellPaintedEvent.OutputObject
    >;

    "ColorBankTriggered(uint256,uint8,uint256,uint256)": TypedContractEvent<
      ColorBankTriggeredEvent.InputTuple,
      ColorBankTriggeredEvent.OutputTuple,
      ColorBankTriggeredEvent.OutputObject
    >;
    ColorBankTriggered: TypedContractEvent<
      ColorBankTriggeredEvent.InputTuple,
      ColorBankTriggeredEvent.OutputTuple,
      ColorBankTriggeredEvent.OutputObject
    >;

    "RewardsWithdrawn(address,uint256)": TypedContractEvent<
      RewardsWithdrawnEvent.InputTuple,
      RewardsWithdrawnEvent.OutputTuple,
      RewardsWithdrawnEvent.OutputObject
    >;
    RewardsWithdrawn: TypedContractEvent<
      RewardsWithdrawnEvent.InputTuple,
      RewardsWithdrawnEvent.OutputTuple,
      RewardsWithdrawnEvent.OutputObject
    >;

    "TimeBankReady(address,uint256)": TypedContractEvent<
      TimeBankReadyEvent.InputTuple,
      TimeBankReadyEvent.OutputTuple,
      TimeBankReadyEvent.OutputObject
    >;
    TimeBankReady: TypedContractEvent<
      TimeBankReadyEvent.InputTuple,
      TimeBankReadyEvent.OutputTuple,
      TimeBankReadyEvent.OutputObject
    >;
  };
}
